var sampleWords = [
    "strawberry",
    "waffle",
    "ice cream",
    "robot",
    "hamster",
    "computer",
    "bush",
    "tulip",
    "bumblebee",
    "waterfall",
    "sand",
    "marshmallow",
    "salad",
    "sunglasses",
    "beetle",
    "car",
    "backpack",
    "pencil",
    "pillow",
    "closet",
    "pants",
    "fork",
    "lake",
    "boat",
    "rock",
    "sleep",
    
]